appadmin/urls.py
from django.urls import path
from appadmin.views import Home, PostCreate, PostList, PostUpdate, Profil, Iklan, Tentang


urlpatterns = [
    path('', Home, name='home'),
    path('about/', Tentang, name='about'),
    path('create/', PostCreate, name='create'),
    path('iklan/', Iklan, name='iklan'),
    path('list/', PostList, name='list'),
    path('profil/', Profil, name='profil'),
    path('update/<slug:slug>/', PostUpdate, name='update'),
]

appsite/urls.py
from django.urls import path
from appsite.views import Home, Kategori, Postingan, Tagpost, Tentang


urlpatterns = [
    path('', Home, name='home'),
    path('about/', Tentang, name='about'),
    path('artikel/<slug:slug>/', Postingan, name='postingan'),
    path('kategori/<slug:slug>/', Kategori, name='kategori'),
    path('tag/<slug:slug>/', Tagpost, name='tag'),
]

baskaratutorial/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('', include(('appsite.urls', 'home'), namespace='appsite')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('dashboard/', include(('appadmin.urls', 'home'), namespace='appadmin')),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appadmin/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from ckeditor.fields import RichTextField
# Create your models here.


class Category(models.Model):
    nama = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(blank=True, null=True, editable=False)

    class Meta:

        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.nama

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nama)
        super(Category, self).save(*args, **kwargs)


class Tag(models.Model):
    nama = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(blank=True, null=True, editable=False)

    class Meta:

        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

    def __str__(self):
        return self.nama

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nama)
        super(Tag, self).save(*args, **kwargs)


class Article(models.Model):
    judul = models.CharField(max_length=255, unique=True)
    kategori = models.ForeignKey(Category, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag)
    body = RichTextField(blank=True, null=True)
    cover = models.ImageField(upload_to='artikel/')
    pinned = models.BooleanField(default=False)
    slug = models.SlugField(blank=True, null=True, editable=False)
    posted = models.DateTimeField(auto_now=False, auto_now_add=True)
    edited = models.DateTimeField(auto_now=True, auto_now_add=False)
    status = models.CharField(
        max_length=50,
        choices=(
            ("1", "published"),
            ("2", "draft"),
        ),
        default=1
    )

    class Meta:

        verbose_name = 'Article'
        verbose_name_plural = 'Articles'

    def __str__(self):
        return self.judul

    def save(self, *args, **kwargs):
        self.slug = slugify(self.judul)
        super(Article, self).save(*args, **kwargs)


class About(models.Model):
    nama = models.CharField(max_length=255, unique=True)
    body = RichTextField(blank=True, null=True)
    slug = models.SlugField(blank=True, null=True, editable=False)

    class Meta:

        verbose_name = 'About'
        verbose_name_plural = 'Abouts'

    def __str__(self):
        return self.nama

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nama)
        super(About, self).save(*args, **kwargs)


class Advertisement(models.Model):
    nama = models.CharField(max_length=50)
    rectangle = models.ImageField(upload_to='ads/')
    rectangle_link = models.URLField(max_length=200)
    leaderboard = models.ImageField(upload_to='ads/')
    leaderboard_link = models.URLField(max_length=200)
    potrait = models.ImageField(upload_to='ads/')
    potrait_link = models.URLField(max_length=200)
    slug = models.SlugField(blank=True, null=True, editable=False)
    durasi = models.DateField(auto_now=False, auto_now_add=False)
    reg = models.DateTimeField(auto_now=False, auto_now_add=True)

    class Meta:

        verbose_name = 'Advertisement'
        verbose_name_plural = 'Advertisements'

    def __str__(self):
        return self.nama

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nama)
        super(Advertisement, self).save(*args, **kwargs)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nama1 = models.CharField(max_length=50)
    nama2 = models.CharField(max_length=50)
    nohp = models.CharField(max_length=12, blank=True, null=True)
    email = models.EmailField(max_length=254)
    slug = models.SlugField(blank=True, null=True, editable=False)

    class Meta:

        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

    def __str__(self):
        return self.nama1

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nama1)
        super(Profile, self).save(*args, **kwargs)

appadmin/forms.py
from django import forms
from django.forms import widgets
from appadmin.models import Article, Profile, Advertisement, About


class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = (
            "judul",
            "kategori",
            "tag",
            "body",
            "cover",
            "pinned",
            "status"
        )
        labels = {
            "judul": "Judul",
            "kategori": "Kategori",
            "tag": "Tag",
            "body": "Body",
            "cover": "Cover",
            "pinned": "Pinned",
            "status": "Status",
        }
        widgets = {
            "judul": widgets.TextInput({"class": "form-control form-control-sm", "placeholder": "Judul Artikel"}),
            "kategori": widgets.Select({"class": "form-select form-select-sm"}),
            "tag": widgets.SelectMultiple({"class": "form-select form-select-sm"}),
            "body": widgets.Textarea({"class": "form-control"}),
            "cover": widgets.FileInput({"class": "form-control form-control-sm", "type": "file"}),
            "pinned": widgets.CheckboxInput({"class": "form-check-input"}),
            "status": widgets.Select({"class": "form-select form-select-sm"}),
        }


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ("nama1", "nama2", "nohp", "email")
        labels = {
            "nama1": "Nama Depan",
            "nama2": "Nama Belakang",
            "nohp": "Nomor Handphone",
            "email": "Email",
        }
        widgets = {
            "nama1": widgets.TextInput({"class": "form-control"}),
            "nama2": widgets.TextInput({"class": "form-control"}),
            "nohp": widgets.TextInput({"class": "form-control"}),
            "email": widgets.EmailInput({"class": "form-control", "type": "email"}),
        }


class AdvertisementForm(forms.ModelForm):

    class Meta:
        model = Advertisement
        fields = (
            "rectangle",
            "rectangle_link",
            "leaderboard",
            "leaderboard_link",
            "potrait",
            "potrait_link",
            "durasi"
        )
        labels = {
            "rectangle": "Rectangle",
            "rectangle_link": "Link",
            "leaderboard": "Leaderboard",
            "leaderboard_link": "Link",
            "potrait": "Potrait",
            "potrait_link": "Link",
            "durasi": "Durasi",
        }
        widgets = {
            "rectangle": widgets.FileInput({"class": "form-control", "type": "file"}),
            "rectangle_link": widgets.URLInput({"class": "form-control"}),
            "leaderboard": widgets.FileInput({"class": "form-control", "type": "file"}),
            "leaderboard_link": widgets.URLInput({"class": "form-control"}),
            "potrait": widgets.FileInput({"class": "form-control", "type": "file"}),
            "potrait_link": widgets.URLInput({"class": "form-control"}),
            "durasi": widgets.DateInput({"class": "form-control", "type": "date"}),
        }


class AboutForm(forms.ModelForm):

    class Meta:
        model = About
        fields = ("body",)
        widgets = {"body": widgets.Textarea({"class": "form-control"})}

appadmin/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.core.paginator import Paginator
from appadmin.models import Article, Category, Profile, Tag, Advertisement, About
from appadmin.forms import ArticleForm, ProfileForm, AdvertisementForm, AboutForm


# Create your views here.
@login_required(login_url="login")
def Home(request):
    pengguna = request.user
    akun = Profile.objects.get(user=pengguna)
    list_artikel = Article.objects.all()
    list_kategori = Category.objects.all()
    list_tag = Tag.objects.all()
    published = list_artikel.filter(status='1')
    draft = list_artikel.filter(status='2')
    paginator = Paginator(list_artikel, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'heading': 'Dashboard', 'akun': akun, 'list_artikel': list_artikel, 'list_kategori': list_kategori,
               'list_tag': list_tag, 'published': published, 'draft': draft, 'page_obj': page_obj}
    return render(request, "appadmin/home.html", context)


@login_required(login_url="login")
def Tentang(request):
    data = About.objects.get(id=1)
    form = AboutForm(instance=data)
    if request.POST:
        form = AboutForm(request.POST, instance=data)
        if form.is_valid():
            form.save()
            return redirect("appadmin:home")
    context = {'form': form}
    return render(request, "appadmin/tentang.html", context)


@login_required(login_url="login")
def Iklan(request):
    list_iklan = Advertisement.objects.get(id=1)
    form = AdvertisementForm(instance=list_iklan)
    if request.POST:
        form = ArticleForm(request.POST, request.FILES, instance=list_iklan)
        if form.is_valid():
            form.save()
            return redirect("appadmin:iklan")
    context = {'list_iklan': list_iklan, 'form': form}
    return render(request, "appadmin/iklan.html", context)


@login_required(login_url="login")
def Profil(request):
    pengguna = request.user
    akun = Profile.objects.get(user=pengguna)
    form = ProfileForm(instance=akun)
    if request.POST:
        form = ProfileForm(request.POST, instance=akun)
        if form.is_valid():
            form.save()
            return redirect("appadmin:home")
    context = {'heading': 'Pengaturan Akun', 'akun': akun, 'form': form}
    return render(request, "appadmin/pengaturan.html", context)


@login_required(login_url="login")
def PostList(request):
    list_artikel = Article.objects.all()
    paginator = Paginator(list_artikel, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'heading': 'Daftar Artikel',
               'list_artikel': list_artikel, 'page_obj': page_obj}
    return render(request, "appadmin/postlist.html", context)


@login_required(login_url="login")
def PostCreate(request):
    form = ArticleForm()
    if request.POST:
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("appadmin:list")
    context = {'heading': 'Buat Artikel', 'form': form}
    return render(request, "appadmin/postform.html", context)


@login_required(login_url="login")
def PostUpdate(request, slug):
    data = Article.objects.get(slug=slug)
    form = ArticleForm(instance=data)
    if request.POST:
        form = ArticleForm(request.POST, request.FILES, instance=data)
        if form.is_valid():
            form.save()
            return redirect("appadmin:list")
    context = {'heading': 'Update Artikel', 'form': form}
    return render(request, "appadmin/postform.html", context)

appadmin/templates/appadmin/home.html
{% extends 'appadmin/index.html' %}{% load static %}

{% block Maincontents %}
<div class="row mb-2">
    <div class="col-md">
        <div class="row mb-1">
            <div class="h5 text-light text-uppercase bg-danger py-1 m-auto">
                <span class="ms-2">Dashboard</span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="row">
                    <div class="col-3">
                        <div class="display-6 text-end">
                            <span class="align-top">{{list_artikel.count}}</span>
                        </div>
                    </div>
                    <div class="col">
                        <div class="text-uppercase">Jumlah Artikel</div>
                        <div class="small">Jumlah Seluruh Artikel</div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="row">
                    <div class="col-3">
                        <div class="display-6 text-end">
                            <span class="align-top">{{published.count}}</span>
                        </div>
                    </div>
                    <div class="col">
                        <div class="text-uppercase">Published</div>
                        <div class="small">Artikel yang di Publish</div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="row">
                    <div class="col-3">
                        <div class="display-6 text-end">
                            <span class="align-top">{{draft.count}}</span>
                        </div>
                    </div>
                    <div class="col">
                        <div class="text-uppercase">Draft</div>
                        <div class="small">Artikel yang di Draft</div>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="h5 text-light text-uppercase bg-danger py-1 m-auto">
                <span class="">Daftar Artikel</span>
            </div>
        </div>
        <div class="row mt-2 mb-2">
            <div class="col-md">
                <div class="table-responsive">
                    <table class="table table-sm table-hover small">
                        <thead>
                            <tr>
                                <td>No</td>
                                <td>Judul</td>
                                <td>Posted</td>
                                <td>Edited</td>
                                <td>Status</td>
                            </tr>
                        </thead>
                        <tbody>
                            {% for artikel in page_obj|dictsortreversed:"edited" %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{artikel.judul}}</td>
                                <td>{{artikel.posted}}</td>
                                <td>{{artikel.edited}}</td>
                                <td>
                                    {% if artikel.status == '1' %}
                                    <span class="badge bg-success">Published</span>
                                    {% else %}
                                    <span class="badge bg-warning">Drafted</span>
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <nav aria-label="Page navigation">
                    <ul class="pagination justify-content-center">
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                <span class="fa fa-angle-double-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                        {% endif %}
                        <li class="page-item"><span class="page-link">{{ page_obj.number }}</span></li>
                        {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                <span class="fa fa-angle-double-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="h5 text-light text-uppercase bg-danger py-1 m-auto">
            <span class="ms-2">Profil</span>
        </div>
        <div class="">
            <div class="py-2">
                <div class="table-responsive">
                    <table class="table table-sm small">
                        <tr>
                            <td>Profil</td>
                            <td>:</td>
                            <td>
                                <span>{{akun.nama1}}</span>
                                <span>{{akun.nama2}}</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Nomor HP</td>
                            <td>:</td>
                            <td>{{akun.nohp}}</td>
                        </tr>
                        <tr>
                            <td>Email</td>
                            <td>:</td>
                            <td>{{akun.email}}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <hr>
    </div>
</div>
{% endblock Maincontents %}

appadmin/templates/appadmin/iklan.html
{% extends 'appadmin/index.html' %}{% load static %}

{% block Maincontents %}
<div class="row mt-3">
    <div class="col-md shadow">
        <div class="row mb-2">
            <div class="h5 text-light text-uppercase bg-danger py-1 m-auto">
                <span class="">Durasi</span>
            </div>
            <div class="col">
                <div class="lead">{{list_iklan.durasi|date:"d M Y"}}</div>
            </div>
        </div>
        <div class="row">
            <div class="col-md">
                <div class="row mb-4">
                    <div class="h5 text-light text-uppercase bg-danger py-1 m-auto">
                        <span class="">Leaderboard</span>
                    </div>
                    <div class="col">
                        <div class="card">
                            <img class="img-fluid" src="{{list_iklan.leaderboard.url}}" alt="list_iklan.leaderboard">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="h5 text-light text-uppercase bg-danger py-1 m-auto">
                        <span class="">Rectangle</span>
                    </div>
                    <div class="col">
                        <div class="card">
                            <img class="img-fluid" src="{{list_iklan.rectangle.url}}" alt="list_iklan.rectangle">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="row">
                    <div class="col">
                        <div class="h5 text-light text-uppercase bg-danger py-1 m-auto">
                            <span class="ms-2">Potrait</span>
                        </div>
                        <div class="card mb-3">
                            <img class="img-fluid" src="{{list_iklan.potrait.url}}" alt="list_iklan.potrait">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card">
                <div class="card-header bg-danger text-light">
                    <p class="card-title text-uppercase text-center p-0 m-0">Upload Banner</p>
                </div>
                <div class="card-body">
                    {{form}}
                </div>
                <div class="card-footer">
                    <div class="d-grid">
                        <button class="btn btn-danger" type="submit">Upload</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock Maincontents %}

appadmin/templates/appadmin/index.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Baskara Tutorial">
    <meta name="keywords" content="Baskara Tutorial">
    <title>Dashboard | Baskara Tutorial</title>
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.2/font/bootstrap-icons.css">
    <style>
        .django-ckeditor-widget {
            width: 100%;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand text-uppercase" href="{% url 'appadmin:home' %}">
                <span class="text-danger">Dashboard</span>
                <span class="text-light">Baskara</span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link text-uppercase" href="{% url 'appadmin:home' %}">Dashboard</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-uppercase" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Manage
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a class="dropdown-item" href="{% url 'appadmin:list' %}">Daftar Artikel</a>
                                <a class="dropdown-item" href="{% url 'appadmin:create' %}">Buat Artikel</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-uppercase" href="{% url 'appadmin:profil' %}">Pengaturan</a>
                    </li>
                    {% if user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link text-uppercase" href="{% url 'appadmin:iklan' %}">Iklan</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-uppercase" href="{% url 'appadmin:about' %}">About</a>
                    </li>
                    {% endif %}
                </ul>
                <div class="d-flex">
                    <a class="btn btn-sm btn-light text-uppercase" href="{% url 'logout' %}">
                        <span class="h6"><i class="bi bi-box-arrow-in-left"></i></span>
                        <span>Keluar</span>
                    </a>
                </div>
            </div>
        </div>
    </nav>
    <div class="container mt-1">{% block Maincontents %}{% endblock Maincontents %}</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

appadmin/templates/appadmin/pengaturan.html
{% extends 'appadmin/index.html' %}{% load static %}
{% block Maincontents %}
<form method="post">
    {% csrf_token %}
    <div class="row justify-content-center">
        <div class="col-md-4 mt-4">
            <div class="card">
                <div class="card-header bg-danger text-light">
                    <p class="card-title text-uppercase text-center p-0 m-0">{{heading}}</p>
                </div>
                <div class="card-body">
                    <div class="form-floating mb-2">
                        {{form.nama1}}
                        {{form.nama1.label_tag}}
                    </div>
                    <div class="form-floating mt-2 mb-2">
                        {{form.nama2}}
                        {{form.nama2.label_tag}}
                    </div>
                    <div class="form-floating mt-2 mb-2">
                        {{form.nohp}}
                        {{form.nohp.label_tag}}
                    </div>
                    <div class="form-floating mt-2 mb-2">
                        {{form.email}}
                        {{form.email.label_tag}}
                    </div>
                </div>
                <div class="card-footer">
                    <div class="d-grid">
                        <button class="btn btn-danger" type="submit">Simpan</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock Maincontents %}

appadmin/templates/appadmin/postform.html
{% extends 'appadmin/index.html' %}{% load static %}

{% block Maincontents %}
<div class="row mt-4">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        <div class="row">
            <div class="col-md-3">
                <div class="row">
                    <div class="col-7">
                        <div class="form-group mt-2 mb-2">{{form.status}}</div>
                    </div>
                    <div class="col-5">
                        <div class="form-check mt-2 mb-2">Pinned Post<span>{{form.pinned}}</span></div>
                    </div>
                </div>
                <div class="form-group mt-2 mb-2">{{form.kategori}}</div>
                <div class="form-group mt-2 mb-2">{{form.tag}}</div>
                <div class="form-group mt-2 mb-2">{{form.cover}}</div>
                <div class="d-grid mt-2 mb-2 text-end"><button class="btn btn-danger" type="submit">Post</button></div>
            </div>
            <div class="col-md">
                <div class="form-group mt-2 mb-2">{{form.judul}}</div>
                <div class="form-group mt-2 mb-2">{{form.body}}</div>
            </div>
        </div>
    </form>
</div>
{% endblock Maincontents %}

appadmin/templates/appadmin/postlist.html
{% extends 'appadmin/index.html' %}{% load static %}

{% block Maincontents %}
<div class="row">
    <div class="col-md">
        <div class="table-responsive">
            <table class="table table-sm table-borderless table-striped table-hover">
                <thead class="bg-danger text-light">
                    <tr>
                        <td class="text-center align-middle">No</td>
                        <td class="text-start align-middle">Judul</td>
                        <td class="text-start align-middle">Kategori</td>
                        <td class="text-center align-middle">Published</td>
                        <td class="text-center align-middle">Edited</td>
                        <td class="text-center align-middle">Status</td>
                    </tr>
                </thead>
                <tbody>
                    {% for artikel in list_artikel|dictsortreversed:"edited" %}
                    <tr>
                        <td class="text-center align-middle">{{forloop.counter}}</td>
                        <td class="text-start align-middle">
                            <a class="text-decoration-none text-dark"
                                href="{% url 'appadmin:update' artikel.slug %}">{{artikel.judul}}</a>
                        </td>
                        <td class="text-start align-middle">{{artikel.kategori}}</td>
                        <td class="text-center align-middle">{{artikel.posted}}</td>
                        <td class="text-center align-middle">{{artikel.edited}}</td>
                        <td class="text-center align-middle">
                            {% if artikel.status == '1' %}
                            <span class="badge bg-success">Published</span>
                            {% else %}
                            <span class="badge bg-warning">Drafted</span>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span class="fa fa-angle-double-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
                {% endif %}
                <li class="page-item"><span class="page-link">{{ page_obj.number }}</span></li>
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span class="fa fa-angle-double-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>
{% endblock Maincontents %}

appadmin/templates/appadmin/tentang.html
{% extends 'appadmin/index.html' %}{% load static %}

{% block Maincontents %}
<form method="post">
    {{form.media}}
    {% csrf_token %}
    <div class="row">
        <div class="col text-end">
            <div class="mt-2 mb-2 d-grid">
                <button class="btn btn-danger" type="submit">Save</button>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                {{form.body}}
            </div>
        </div>
    </div>
</form>
{% endblock Maincontents %}