appsite/urls.py
from django.urls import path
from appsite.views import Home, Kategori, Postingan, Tagpost, Tentang


urlpatterns = [
    path('', Home, name='home'),
    path('about/', Tentang, name='about'),
    path('artikel/<slug:slug>/', Postingan, name='postingan'),
    path('kategori/<slug:slug>/', Kategori, name='kategori'),
    path('tag/<slug:slug>/', Tagpost, name='tag'),
]

baskaratutorial/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('', include(('appsite.urls', 'home'), namespace='appsite')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('dashboard/', include(('appadmin.urls', 'home'), namespace='appadmin')),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appsite/models.py
from django.db import models

# Create your models here.

appsite/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from appadmin.models import About, Advertisement, Article, Category, Tag


# Create your views here.
def Home(request):
    iklan = Advertisement.objects.get(id=1)
    list_artikel = Article.objects.all().filter(status='1')
    list_kategori = Category.objects.all()
    list_tag = Tag.objects.all()
    list_pin = list_artikel.filter(pinned=1)
    paginator = Paginator(list_artikel, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'heading': 'Homepage', 'list_artikel': list_artikel,'list_kategori': list_kategori, 'list_tag': list_tag, 'list_pin': list_pin, 'iklan': iklan, 'page_obj': page_obj}
    return render(request, "appsite/home.html", context)


def Tentang(request):
    iklan = Advertisement.objects.get(id=1)
    about = About.objects.get(id=1)
    list_kategori = Category.objects.all()
    context = {'heading': 'About', 'list_kategori': list_kategori,'about': about, 'iklan': iklan}
    return render(request, "appsite/about.html", context)


def Kategori(request, slug):
    iklan = Advertisement.objects.get(id=1)
    list_artikel = Article.objects.all().filter(status='1')
    list_kategori = Category.objects.all()
    list_tag = Tag.objects.all()
    list_pin = list_artikel.filter(pinned=1)
    data = list_kategori.get(slug=slug)
    filter_post = list_artikel.filter(kategori=data)
    paginator = Paginator(filter_post, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'heading': 'Kategori', 'list_artikel': list_artikel, 'list_kategori': list_kategori,'list_tag': list_tag, 'list_pin': list_pin, 'filter_post': filter_post, 'iklan': iklan, 'page_obj': page_obj}
    return render(request, "appsite/kategori.html", context)


def Tagpost(request, slug):
    iklan = Advertisement.objects.get(id=1)
    list_artikel = Article.objects.all().filter(status='1')
    list_kategori = Category.objects.all()
    list_tag = Tag.objects.all()
    list_pin = list_artikel.filter(pinned=1)
    data = list_tag.get(slug=slug)
    filter_post = list_artikel.filter(tag=data)
    paginator = Paginator(filter_post, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'heading': 'Tag', 'list_artikel': list_artikel, 'list_kategori': list_kategori,'list_tag': list_tag, 'list_pin': list_pin, 'filter_post': filter_post, 'iklan': iklan, 'page_obj': page_obj}
    return render(request, "appsite/tag.html", context)


def Postingan(request, slug):
    iklan = Advertisement.objects.get(id=1)
    list_artikel = Article.objects.all().filter(status='1')
    list_kategori = Category.objects.all()
    list_tag = Tag.objects.all()
    list_pin = list_artikel.filter(pinned=1)
    artikel = list_artikel.get(slug=slug)
    context = {'heading': 'Tag', 'list_artikel': list_artikel, 'list_kategori': list_kategori,'list_tag': list_tag, 'list_pin': list_pin, 'artikel': artikel, 'iklan': iklan}
    return render(request, "appsite/artikel.html", context)

appsite/templates/appsite/about.html
{% extends 'appsite/index.html' %}{% load static %}

{% block Maincontents %}
<div class="row">
    <div class="col-md">
        <div class="h4 text-center text-light text-uppercase bg-danger py-1 m-auto">
            <span class="ms-2">{{about.nama}}</span>
        </div>
        <div class="">
            {{about.body|safe}}
        </div>
    </div>
</div>
{% endblock Maincontents %}

appsite/templates/appsite/artikel.html
{% extends 'appsite/index.html' %}{% load static %}

{% block Maincontents %}
<div class="row">
    <div class="col-md mb-2">
        <div class="mb-2">
            <img class="d-block w-100" src="{{artikel.cover.url}}" alt="{{artikel.slug}}">
        </div>
        <div class="row">
            <div class="h3 text-center">{{artikel.judul}}</div>
            <div class="small text-center fst-italic">
                <span>Kategori :</span>
                <span class="fw-bold">
                    <a class="text-decoration-none text-danger"
                        href="{% url 'appsite:kategori' artikel.kategori.slug %}">{{artikel.kategori}}</a>
                </span>
            </div>
            <div class="mt-2">
                {{artikel.body|safe}}
            </div>
        </div>
    </div>
    <div class="col-md-3">
        {% include 'appsite/sidebar.html' %}
    </div>
</div>
{% endblock Maincontents %}

appsite/templates/appsite/home.html
{% extends 'appsite/index.html' %}{% load static %}

{% block Maincontents %}
<div class="row">
    <div class="col-md mb-2">
        <div class="h5 text-light text-uppercase bg-danger py-1 m-auto">
            <span class="ms-2">Featured</span>
        </div>
        <div id="carousel-page1" class="carousel slide" data-bs-ride="false">
            <div class="carousel-inner">
                {% for artikel in list_pin|dictsortreversed:"edited" %}
                <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}"
                    id="Slide {{ forloop.counter }}">
                    <a href="{% url 'appsite:postingan' artikel.slug %}">
                        <img src="{{artikel.cover.url}}" class="d-block w-100" alt="{{artikel.slug}}"
                            style="width: 100%; height: 100%; object-fit: cover;">
                    </a>
                    <div class="carousel-caption d-none d-md-block">
                        <h5>{{artikel.judul}}</h5>
                        <p>{{artikel.body|truncatechars:100|safe}}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carousel-page1" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carousel-page1" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
        <div class="row mt-2">
            <div class="col-md">
                <div class="h5 text-light text-uppercase bg-danger py-1 m-auto">
                    <span class="ms-2">Artikel Terbaru</span>
                </div>
                <div class="mt-2">
                    {% for artikel in page_obj|dictsortreversed:"posted" %}
                    <div class="card mb-2">
                        <div class="row">
                            <div class="col-3">
                                <img class="img-fluid" src="{{artikel.cover.url}}" alt="{{artikel.slug}}"
                                    style="width: 100%; height: 100%; object-fit: cover;">
                            </div>
                            <div class="col p-0 m-0">
                                <div class="card-body">
                                    <div class="badge badge-sm bg-danger text-light">
                                        {{artikel.kategori}}
                                    </div>
                                    <h5>
                                        <a class="text-decoration-none text-danger"
                                            href="{% url 'appsite:postingan' artikel.slug %}">{{artikel.judul}}</a>
                                    </h5>
                                    <div class="small fst-italic text-muted">
                                        {{artikel.body|truncatechars:"150"|safe}}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <nav aria-label="Page navigation">
                    <ul class="pagination justify-content-center">
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                <span class="fa fa-angle-double-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                        {% endif %}
                        <li class="page-item"><span class="page-link">{{ page_obj.number }}</span></li>
                        {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                <span class="fa fa-angle-double-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        {% include 'appsite/sidebar.html' %}
    </div>
</div>
{% endblock Maincontents %}

appsite/templates/appsite/index.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Baskara Tutorial">
    <meta name="keywords" content="Baskara Tutorial">
    <title>Baskara Tutorial</title>
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.2/font/bootstrap-icons.css">
</head>

<body>
    <div class="row d-none d-lg-block">
        <img class="img-fluid" src="{% static 'img/home.png' %}" alt="">
    </div>
    <nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand text-uppercase" href="{% url 'appsite:home' %}">
                <span class="text-danger">Baskara</span>
                <span class="text-light">Tutorial</span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link text-uppercase" href="{% url 'appsite:home' %}">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-uppercase" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Kategori
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for kategori in list_kategori %}
                            <li>
                                <a class="dropdown-item"
                                    href="{% url 'appsite:kategori' kategori.slug %}">{{kategori}}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-uppercase" href="{% url 'appsite:about' %}">About</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container mt-4">
        {% block Maincontents %}{% endblock Maincontents %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

appsite/templates/appsite/kategori.html
{% extends 'appsite/index.html' %}{% load static %}

{% block Maincontents %}
<div class="row">
    <div class="col-md mb-2">
        <div class="h5 text-light text-uppercase bg-danger py-1 m-auto">
            <span class="ms-2">{{heading}}</span>
        </div>
        <div class="row mt-2">
            <div class="col-md">
                {% for artikel in page_obj|dictsortreversed:"edited" %}
                <div class="card mb-3">
                    <div class="row g-0">
                        <div class="col-3">
                            <img src="{{artikel.cover.url}}" class="img-fluid" alt="{{artikel.judul}}"
                                style="width: 100%; height: 100%; object-fit: cover;">
                        </div>
                        <div class="col">
                            <div class="p-2">
                                <h5 class="badge bg-danger">
                                    <a class="text-decoration-none text-light"
                                        href="{% url 'appsite:kategori' artikel.kategori.slug %}">{{artikel.kategori}}</a>
                                </h5>
                                <p class="h6 fs-4">
                                    <a class="text-decoration-none text-danger"
                                        href="{% url 'appsite:postingan' artikel.slug %}">{{artikel.judul}}</a>
                                </p>
                                <p class=" fst-italic text-muted">
                                    <span class="small">{{artikel.body|truncatechars:100|safe}}</span>
                                </p>
                                <span class="card-text"><small class="text-muted">{{artikel.posted}}</small></span>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <nav aria-label="Page navigation">
                    <ul class="pagination justify-content-center">
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                <span class="fa fa-angle-double-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                        {% endif %}
                        <li class="page-item"><span class="page-link">{{ page_obj.number }}</span></li>
                        {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                <span class="fa fa-angle-double-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        {% include 'appsite/sidebar.html' %}
    </div>
</div>
{% endblock Maincontents %}

appsite/templates/appsite/sidebar.html
{% load static %}
<div class="h5 text-light text-uppercase bg-danger py-1 m-auto">
    <span class="ms-2">Kategori</span>
</div>
<div class="">
    <div class="p-2">
        {% for kategori in list_kategori %}
        <a class="btn btn-sm btn-outline-danger" href="{% url 'appsite:kategori' kategori.slug %}">{{kategori}}</a>
        {% endfor %}
    </div>
</div>
<hr>
<div class="">
    <a href="{{iklan.rectangle_link}}" target="_blank" rel="noopener noreferrer">
        <img class="d-block w-100" src="{{iklan.rectangle.url}}" alt="{{iklan}}" style="width: 100%; height: 100%; object-fit: cover;">
    </a>
</div>
<hr>
<div class="h5 text-light text-uppercase bg-danger py-1 m-auto">
    <span class="ms-2">Tag</span>
</div>
<div class="">
    <div class="p-2">
        {% for tag in list_tag %}
        <a class="btn btn-sm btn-outline-danger" href="{% url 'appsite:tag' tag.slug %}">{{tag}}</a>
        {% endfor %}
    </div>
</div>
<hr>
<div class="d-none d-lg-block">
    <a href="{{iklan.potrait_link}}" target="_blank" rel="noopener noreferrer">
        <img class="d-block w-100" src="{{iklan.potrait.url}}" alt="{{iklan}}"
            style="width: 100%; height: 100%; object-fit: cover;">
    </a>
</div>
<hr>

appsite/templates/appsite/tag.html
{% extends 'appsite/index.html' %}{% load static %}

{% block Maincontents %}
<div class="row">
    <div class="col-md mb-2">
        <div class="h5 text-light text-uppercase bg-danger py-1 m-auto">
            <span class="ms-2">{{heading}}</span>
        </div>
        <div class="row mt-2">
            <div class="col-md">
                {% for artikel in page_obj|dictsortreversed:"edited" %}
                <div class="card mb-3">
                    <div class="row g-0">
                        <div class="col-3">
                            <img src="{{artikel.cover.url}}" class="img-fluid" alt="{{artikel.judul}}"
                                style="width: 100%; height: 100%; object-fit: cover;">
                        </div>
                        <div class="col">
                            <div class="p-2">
                                <h5 class="badge bg-danger">
                                    <a class="text-decoration-none text-light"
                                        href="{% url 'appsite:kategori' artikel.kategori.slug %}">{{artikel.kategori}}</a>
                                </h5>
                                <p class="h6 fs-4">
                                    <a class="text-decoration-none text-danger"
                                        href="{% url 'appsite:postingan' artikel.slug %}">{{artikel.judul}}</a>
                                </p>
                                <p class=" fst-italic text-muted">
                                    <span class="small">{{artikel.body|truncatechars:100|safe}}</span>
                                </p>
                                <span class="card-text"><small class="text-muted">{{artikel.posted}}</small></span>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <nav aria-label="Page navigation">
                    <ul class="pagination justify-content-center">
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                <span class="fa fa-angle-double-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                        {% endif %}
                        <li class="page-item"><span class="page-link">{{ page_obj.number }}</span></li>
                        {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                <span class="fa fa-angle-double-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        {% include 'appsite/sidebar.html' %}
    </div>
</div>
{% endblock Maincontents %}